### ISSUE TITLE
1.2 cannot run

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_favorites#20]
```
Python 3.8
Startup: 640ms, plugins: 0ms ()
Init: cuda_favorites
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_favorites/__init__.py", line 1, in <module>
    from .cd_favs import Command
  File "/home/user/.config/cudatext/py/cuda_favorites/cd_favs.py", line 13, in <module>
    from    .cd_plug_lib    import *
ModuleNotFoundError: No module named 'cuda_favorites.cd_plug_lib'
Init: cuda_addonman
```

**Comment by kvichans** [comment]
Сори
Были перепутаны шаги при обновлении в ГХ
Обновил в ГХ
